FROM alpine:edge

RUN apk add -U --no-cache ntfy

RUN echo "nonroot:x:65534:65534:nonroot:/home/nonroot:/usr/sbin/nologin" | tee -a /etc/passwd && \
  echo "nonroot:x:65534:nonroot" | tee -a /etc/group

USER nonroot

CMD [ "ntfy", "serve" ]
